# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0004_remove_invoicedetail_invoice'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceDetail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoice_details.InvoiceDetail'),
            preserve_default=False,
        ),
    ]
