# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('second_surname', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=21)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('partner', models.CharField(choices=[('NO_PARTNER', 'No socio'), ('PARTNER_A', 'Tipo A'), ('PARTNER_B', 'Tipo B'), ('PARTNER_C', 'Tipo C')], default='NO_PARTNER', max_length=255)),
                ('partner_release_date', models.DateField()),
                ('known_for', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('INTERNET', 'Internet'), ('RADIO', 'Radio'), ('BOCA_A_BOCA', 'Boca a boca'), ('LOCALIZACION', 'Localizaci\xf3n'), ('PUBLICIDAD_IMPRESA', 'Publicidad impresa'), ('OTROS', 'Otros')], default='FACEBOOK', max_length=255)),
                ('lopd', models.BooleanField(default=False)),
                ('lopd_channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=255)),
                ('lopd_options', multiselectfield.db.fields.MultiSelectField(choices=[('FOTODEPILACION', 'Fotodepilaci\xf3n'), ('MANICURA', 'Manicura'), ('PEDICURA', 'Pedicura'), ('MAQUILLAJE', 'Maquillaje'), ('TRATAMIENTOS_FACIALES', 'Tratamientos faciales'), ('TRATAMIENTOS_CORPORALES', 'Tratamientos corporales'), ('CEJAS_Y_PESTANAS', 'Cejas y pesta\xf1as')], default=None, max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
