# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('invoices', '__first__'),
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoices.Invoice')),
                ('quantity', models.IntegerField(default=0)),
                ('vat', models.IntegerField(choices=[(21, 'GENERAL'), (10, 'REDUCIDO'), (4, 'SUPERREDUCIDO'), (0, 'EXENTO')], default=21)),
                ('discount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
