# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('invoices', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('vat', models.IntegerField(choices=[(21, 'GENERAL'), (10, 'REDUCIDO'), (4, 'SUPERREDUCIDO'), (0, 'EXENTO')], default=21)),
                ('discount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('CASH', 'Met\xe1lico'), ('CREDIT_CARD', 'Tarjeta de cr\xe9dito'), ('PREPAID_CARD', 'Bono')], default='CASH', max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
                ('prepaid_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.PrepaidCard')),
                ('product', models.ManyToManyField(blank=True, to='products.Product')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invoicedetail',
            unique_together=set([('invoice', 'id')]),
        ),
    ]
