# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='services.Service'),
        ),
    ]
