# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170313_2150'),
        ('services', '0001_initial'),
        ('invoice_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='product',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='service',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='service',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
