# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0002_auto_20170309_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoices.Invoice'),
        ),
    ]
