# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0002_auto_20170327_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='discount',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Met\xe1lico'), ('CREDIT_CARD', 'Tarjeta de cr\xe9dito'), ('PREPAID_CARD', 'Bono')], default='CASH', max_length=255),
        ),
    ]
