# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0003_auto_20170514_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='vat',
        ),
    ]
