# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0003_auto_20170326_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
    ]
