# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0004_remove_invoicedetail_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='vat',
            field=models.IntegerField(choices=[(21, 'GENERAL'), (10, 'REDUCIDO'), (4, 'SUPERREDUCIDO'), (0, 'EXENTO')], default=21),
        ),
    ]
