# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0004_auto_20170309_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='vat',
            field=models.IntegerField(choices=[(21, 'GENERAL'), (10, 'REDUCIDO'), (4, 'SUPERREDUCIDO'), (0, 'SIN IVA')], default=21),
        ),
    ]
