# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0005_auto_20170309_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='vat',
            field=models.IntegerField(choices=[(21, '21'), (10, '10'), (4, '4'), (0, '0')], default=21),
        ),
    ]
