# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0007_auto_20170310_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='vat',
            field=models.IntegerField(choices=[(21, 21), (10, 10), (4, 4), (0, 0)], default=21),
        ),
    ]
