# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
