# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170514_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CAFETERAPIA', 'Cafeterapia'), ('FITOTERAPIA', 'Fitoterapia'), ('HIALUR\xd3NICO', 'Hialur\xf3nico'), ('LINEA_ESENCIAL', 'L\xednea esencial'), ('LINFODRENANTE', 'Linfodrenante'), ('PERLAS', 'Perlas'), ('PIELES_GRASAS', 'Pieles grasas'), ('PIELES_SENSIBLES', 'Pieles sensibles'), ('METODOS_DE_PAGO', 'M\xe9todos de pago'), ('UNCATEGORIZED', 'Sin categorizar')], default='UNCATEGORIZED', max_length=255),
        ),
    ]
